---
# defaults file for apt_sources
apt_sources_list_path_ubuntu_22: "/etc/apt/sources.list"
apt_sources_list_path_ubuntu_24: "/etc/apt/sources.list.d/ubuntu.sources"
apt_sources_list_regexp: "http://[^ ]*archive.ubuntu.com/ubuntu/"
apt_sources_list_replace: "http://jp.archive.ubuntu.com/ubuntu/"
