---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos-7
    image: nakahiro386/centos7-systemd:latest
    command: ""
    privileged: true
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    environment:
      FTP_PROXY: ${FTP_PROXY}
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      NO_PROXY: ${NO_PROXY}
      ftp_proxy: ${ftp_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
  - name: oraclelinux-7
    image: nakahiro386/oraclelinux7-systemd:latest
    command: ""
    privileged: true
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    environment:
      FTP_PROXY: ${FTP_PROXY}
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      NO_PROXY: ${NO_PROXY}
      ftp_proxy: ${ftp_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
  - name: oraclelinux-8
    image: nakahiro386/oraclelinux8-systemd:latest
    command: ""
    privileged: true
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    environment:
      FTP_PROXY: ${FTP_PROXY}
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      NO_PROXY: ${NO_PROXY}
      ftp_proxy: ${ftp_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
  - name: ubuntu-2204
    image: nakahiro386/ubuntu2204-systemd:latest
    command: ""
    privileged: true
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    environment:
      FTP_PROXY: ${FTP_PROXY}
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      NO_PROXY: ${NO_PROXY}
      ftp_proxy: ${ftp_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
  - name: ubuntu-2404
    image: nakahiro386/ubuntu2404-systemd:latest
    command: ""
    privileged: true
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    environment:
      FTP_PROXY: ${FTP_PROXY}
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      NO_PROXY: ${NO_PROXY}
      ftp_proxy: ${ftp_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
provisioner:
  name: ansible
  env:
    ANSIBLE_VERBOSITY: 0
    HTTP_PROXY: ${HTTP_PROXY}
    HTTPS_PROXY: ${HTTPS_PROXY}
    http_proxy: ${http_proxy}
    https_proxy: ${https_proxy}
  config_options:
    defaults:
      gathering: smart
      fact_caching: jsonfile
      fact_caching_connection: /tmp/molecule_facts_cache
      fact_caching_timeout: 7200
      diff: true
      stdout_callback: yaml
      keep_remote_files: true
  inventory:
    host_vars:
      centos-7:
        ansible_user: ansible
      oraclelinux-7:
        ansible_user: ansible
      oraclelinux-8:
        ansible_user: ansible
      ubuntu-2204:
        ansible_user: ansible
      ubuntu-2404:
        ansible_user: ansible
verifier:
  name: ansible
