---
- name: Verify
  hosts: all
  gather_facts: false
  vars:
    _locale: "ja_JP.UTF-8"
    _timezone: "Asia/Tokyo"
  tasks:
    - name: Check locale
      block:
        - name: Get locale
          ansible.builtin.command: "localectl status"
          register: get_locale
          check_mode: false
          changed_when: false

        - name: Check locale
          ansible.builtin.assert:
            that:
              - ('LANG=' + _locale) in get_locale.stdout
          when: not ansible_check_mode

    - name: Check timezone
      block:
        - name: Get timezone
          ansible.builtin.command: "timedatectl status"
          register: get_timezone
          check_mode: false
          changed_when: false

        - name: Check timezone
          ansible.builtin.assert:
            that:
              - _timezone in get_timezone.stdout
          when: not ansible_check_mode
