---
# handlers file for docker_ce
- name: Restarted docker.service
  ansible.builtin.systemd_service:
    name: docker.service
    state: restarted
    daemon_reload: true
  ignore_errors: "{{ ansible_check_mode }}"
  tags:
    - docker_ce
    - system
    - config
