---
- name: Converge
  hosts: all
  module_defaults:
    ansible.builtin.setup:
      gather_subset:
        - 'min'
        - 'virtual'
        # - 'all'
        # - '!network'
        # - '!hardware'
  gather_facts: true
  vars:
    FPT_PROXY: "{{ lookup('env', 'FPT_PROXY', default=omit) }}"
    HTTP_PROXY: "{{ lookup('env', 'HTTP_PROXY', default=omit) }}"
    HTTPS_PROXY: "{{ lookup('env', 'HTTPS_PROXY', default=omit) }}"
    NO_PROXY: "{{ lookup('env', 'NO_PROXY', default=omit) }}"
    fpt_proxy: "{{ lookup('env', 'fpt_proxy', default=omit) }}"
    http_proxy: "{{ lookup('env', 'http_proxy', default=omit) }}"
    https_proxy: "{{ lookup('env', 'https_proxy', default=omit) }}"
    no_proxy: "{{ lookup('env', 'no_proxy', default=omit) }}"
    apt_ppa_repository_repositories:
      - name: "git-core-ubuntu-ppa-{{ ansible_distribution_release }}"
        uris: "https://ppa.launchpadcontent.net/git-core/ppa/ubuntu"
        components: main
        signed_by: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xE1DD270288B4E6030699E45FA1715D88E1DF1F24"
    docker_ce_daemon_json_value:
      exec-opts: ["native.cgroupdriver=systemd"]
    systemd_timesyncd_force_deploy_build_conf: true
  environment:
    FPT_PROXY: "{{ lookup('env', 'FPT_PROXY', default=omit) }}"
    HTTP_PROXY: "{{ lookup('env', 'HTTP_PROXY', default=omit) }}"
    HTTPS_PROXY: "{{ lookup('env', 'HTTPS_PROXY', default=omit) }}"
    NO_PROXY: "{{ lookup('env', 'NO_PROXY', default=omit) }}"
    fpt_proxy: "{{ lookup('env', 'fpt_proxy', default=omit) }}"
    http_proxy: "{{ lookup('env', 'http_proxy', default=omit) }}"
    https_proxy: "{{ lookup('env', 'https_proxy', default=omit) }}"
    no_proxy: "{{ lookup('env', 'no_proxy', default=omit) }}"
  tasks:
    - name: "Include nakahiro386.system.proxy"
      ansible.builtin.include_role:
        name: "nakahiro386.system.proxy"
        apply:
          become: true
    - name: "Include nakahiro386.system.apt_sources"
      ansible.builtin.include_role:
        name: "nakahiro386.system.apt_sources"
        apply:
          become: true
    - name: "Include nakahiro386.system.apt_ppa_repository"
      ansible.builtin.include_role:
        name: "nakahiro386.system.apt_ppa_repository"
        apply:
          become: true
    - name: "Include nakahiro386.system.locale"
      ansible.builtin.include_role:
        name: "nakahiro386.system.locale"
        apply:
          become: true
    - name: "Include nakahiro386.system.timezone"
      ansible.builtin.include_role:
        name: "nakahiro386.system.timezone"
        apply:
          become: true
    - name: "Include nakahiro386.systemd_timesyncd"
      ansible.builtin.include_role:
        name: "nakahiro386.system.systemd_timesyncd"
        apply:
          become: true
    - name: "Include nakahiro386.system.docker_ce"
      ansible.builtin.include_role:
        name: "nakahiro386.system.docker_ce"
        apply:
          become: true
