---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos-7
    image: docker.io/geerlingguy/docker-centos7-ansible:python3
    command: ""
    privileged: true
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    environment:
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
  - name: centos-8
    image: docker.io/geerlingguy/docker-centos8-ansible:latest
    command: ""
    privileged: true
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    environment:
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
  - name: ubuntu-2204
    image: docker.io/geerlingguy/docker-ubuntu2204-ansible:latest
    command: ""
    privileged: true
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    environment:
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
provisioner:
  name: ansible
  env:
    ANSIBLE_VERBOSITY: 0
    HTTP_PROXY: ${HTTP_PROXY}
    HTTPS_PROXY: ${HTTPS_PROXY}
    http_proxy: ${http_proxy}
    https_proxy: ${https_proxy}
verifier:
  name: ansible
