---
# handlers file for journald
- name: Restart systemd-journald.service
  ansible.builtin.systemd_service:
    name: systemd-journald.service
    state: restarted
  ignore_errors: "{{ ansible_check_mode }}"
  tags:
    - journald
    - system
    - config
