---
# tasks file for apt_sources
- name: Configure apt_sources tasks
  tags:
    - apt_sources
    - system
    - config
  when:
    - ansible_pkg_mgr == 'apt'
    - ansible_distribution == 'Ubuntu'
  block:
    - name: Set _apt_sources_list_path
      ansible.builtin.set_fact:
        _apt_sources_list_path: "{{ lookup('vars', 'apt_sources_list_path_' + (ansible_distribution | lower) + '_' + ansible_distribution_major_version) }}"
    - name: Replace sources.list
      ansible.builtin.replace:
        dest: "{{ _apt_sources_list_path }}"
        regexp: "{{ apt_sources_list_regexp }}"
        replace: "{{ apt_sources_list_replace }}"
        backup: true
      register: sources_list

    - name: Update cache if sources.list changed
      ansible.builtin.apt:
        update_cache: true
      when:
        - not ansible_check_mode
        - sources_list.changed
